[package]
name = "threaded-hasher"
version = "0.1.0"
authors = ["Stephen Battista <stephen.battista@gmail.com>"]
edition = "2018"

[dependencies]
ring = "0.17.8"
data-encoding = "2.6.0"
scoped_threadpool = "0.1.9"
clap = "2.*.*"
indicatif = "0.17.8"
num_cpus = "1.16.0"
walkdir ="2.5.0"
